server:
  port: 7676
  servlet:
    context-path: /
  shutdown: graceful
  http:
    port: 7676

spring:
  config:
    activate:
      on-profile: local
  ############################################################
  # DataSource 설정
  ############################################################

#  session:
#    store-type: jdbc
#    jdbc:
#      initialize-schema: always

#  ############################################################
#  # Restful Client Configuration
#  ############################################################
#  restTemplate:
#    factory:
#      readTimeout: 60000
#      connectTimeout: 60000
#    httpClient:
#      maxConnTotal: 100
#      maxConnPerRoute: 5